version: '2.10.2'

services:
  # MongoDB Services
  mongo_db:
    container_name: preptimeDB
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - ./db:/data/db

  # Node.js API Services
  api:
    build: .
    container_name: preptimeAPI
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/app
    environment:
      - PORT=5000
      - DB_HOST=mongo_db
      - DB_PORT=27017
      - DB_NAME=preptime
    depends_on:
      - mongo_db

# volumes:
#   mongo_db: {}